### ISSUE TITLE
Integrate flysystem modal into CMS page and block form

### ISSUE THREAD

**Issue by robin-homberg** [Flagbit/Magento2-Flysystem#2]
Since the modal is already integrated into the products and categories form, it would be also great to add access to the modal inside the forms for cms pages and blocks.

An idea not to overflood the page with to many buttons, and add easily the button also for the wysiwyg, and also for the html view of the content, an idea is to place the button to open the new flysystem browser inside the default cms mediabrowser. So you can "swap" the modal from the default to the flysystem.... and also backwards.

**Comment by BrocksiNet** [comment]
This is done in Version [0.1.7](https://github.com/Flagbit/Magento2-Flysystem/releases/tag/0.1.7)
