### ISSUE TITLE
Magento2-Flysystem Question

### ISSUE THREAD

**Issue by webpaldev** [Flagbit/Magento2-Flysystem#38]
I have a question about the module:  Its propose is feed magneto media from external source (sftp, ftp, etc) right?! and have nothing store locally correct?

**Comment by robin-homberg** [comment]
The module delivers some classes for integrating external file sources using Flysystem. Also the module extends Magento2 Adminpanel functionality so you can manage files in the external file source, or insert images in products, categories and cms-pages/-blocks/etc. from the external source.
Inserting an image from the external source will result in the image beeing downloaded and stored in the magento2 media directory. The magento2 core functionality in the storefront is unchanged.

**Comment by webpaldev** [comment]
@robin-homberg [robin-homberg](https://github.com/robin-homberg)

Thank you for the clarification!
