### ISSUE TITLE
Move github wiki into Repository

### ISSUE THREAD

**Issue by robin-homberg** [Flagbit/Magento2-Flysystem#9]
The github wiki should also be added as files to the repository. So contributors are able also to update the wiki according to their changes.

**Comment by marius-wieschollek** [comment]
Adding the files sounds linke duplicating stuff to me. Since the wiki is a git too, you could try a submodule or this: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by BrocksiNet** [comment]
This is done.

**Repo for wiki can be found here:**
https://github.com/Flagbit/Magento2-Flysystem-Wiki
